<table class="GameContentHeader">
<tr align="center">
<td class="icon"><div id="##GAMECONTENTID##" class="loading" width='64', height='64'></div></td>
<td class="gameName"><a href="javascript:postwith('/gamedetails.html?contenttype=##GAMECONTENTTYPE##&titleid=##GAMETITLEID##&contentid=##GAMECONTENTID##', {sessionid:'##SESSIONID##'})">##GAMENAME##</a></td>
<td class="titleID">##GAMETITLEID##</td><td class="titleID">##GAMEMEDIAID##</td>
<td class="gamePath">##GAMEPATH##</td>
<td class="gameAction">[&nbsp;<a class="optionlink" href="javascript:postwith('/launch', {sessionid:'##SESSIONID##', contentid:'##GAMECONTENTID##', Action:'launch'})">Launch</a>&nbsp;]</td>
</tr>
</table> 
