<table class="PathList">
	<tr align="center">
		<td class="option">[&nbsp;<a class="optionlink" href="javascript:postwith('/paths.html', {sessionid:'##SESSIONID##', pathid:'##PATHID##', Action:'scan'})">Scan</a>&nbsp;]&nbsp;&nbsp;[&nbsp;<a class="optionlink" href="javascript:postwith('/paths.html', {sessionid:'##SESSIONID##', pathid:'##PATHID##', Action:'remove'})" title="Remove">Remove</a>&nbsp;]</td>
		<td class="devkit">##PATHDEVKITTYPE##</td>
		<td class="retail">##PATHRETAILTYPE##</td>
		<td class="depth">##PATHDEPTH##</td>
		<td class="path">##PATHPATH##</td>
	</tr>
</table>